### ISSUE TITLE
OpenJDK instead of Oracle

### ISSUE THREAD

**Issue by antoinetran** [sheepkiller/kafka-manager-docker#7]
Hi,

I saw that this container uses Oracle Java. Its license is quite restrictive, and my company would rather use OpenJDK. Do you think this is a good idea? There is no reason that kafka manager would not work, and it would reduce the dependency from Oracle.

Thank you.

**Comment by sheepkiller** [comment]
Hi,

You're right, using Oracle Java is pretty "unsafe". I have few pending changes (switching to alpine linux, run KM as non root user and also switching to openjdk), but all those changes require a roadmap since my docker image seems to be popular and used by several projects (ex: mantl). I'll keep your issue open until next release, when I publish roadmap for the next 3 releases. My first guess is:
- release + 1: roadmap
- release + 2: defaulting to openjdk
- release + 3: switching to non root user
- release +4: switching to alpine linux

Thank you for reminding me to make the move

**Comment by dsmiley** [comment]
+1 to your plan.  This image is very heavy right now.  It shouldn't need to compile anything -- take an official release.

Also, I think the play pid file should be redirected to /dev/null -- there's no point in having the pid in docker, and I've seen it prevent restarting the app if it didn't stop gracefully.

**Comment by sheepkiller** [comment]
Hi @dsmiley,

I'd be happy to use a binary release. Unfortunatly, there's no official one. Since the release process changed several times in the past, I'm currently sticking to my git+jdk build process. If you want a lighter image (~140MB), you can find an experimental alpine-based one using the `alpine` tag.

**Comment by Raboo** [comment]
@antoinetran I've created a new openjdk based image, https://github.com/deltaprojects/kafka-manager-docker

**Comment by antoinetran** [comment]
Excellent. Closing it.

**Comment by Raboo** [comment]
It's still building the image since i just pushed it, but it should be available in docker hub in a few minutes.
